# Generated by Django 2.1.2 on 2018-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0002_remove_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.BinaryField(),
        ),
    ]
