# Generated by Django 2.1.2 on 2018-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0004_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.BinaryField(editable=True),
        ),
    ]
