# Generated by Django 2.1.2 on 2018-11-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0012_auto_20181120_1837'),
        ('spcv1', '0012_auto_20181122_1103'),
    ]

    operations = [
    ]
