# Generated by Django 2.1.2 on 2018-11-23 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spcv1', '0013_merge_20181123_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryption',
            name='last_enc_update',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='encryption',
            name='locked',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='encryption',
            unique_together={('user', 'encrypted')},
        ),
    ]
