# Generated by Django 2.1.2 on 2018-11-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0015_auto_20181123_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_files',
            name='data',
            field=models.CharField(default=' ', max_length=100000000),
        ),
        migrations.AddField(
            model_name='shared_files',
            name='md5sum',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
