# Generated by Django 2.1.2 on 2018-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0005_auto_20181017_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(max_length=10000000000),
        ),
    ]
