# Generated by Django 2.1.2 on 2018-10-20 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spcv1', '0006_auto_20181017_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('user', 'path')},
        ),
    ]
