# Generated by Django 2.1.2 on 2018-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0007_auto_20181020_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5sum',
            field=models.CharField(default='12345', max_length=100),
            preserve_default=False,
        ),
    ]
