# Generated by Django 2.1.2 on 2018-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0010_shared_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='safe',
            field=models.CharField(default='T', max_length=1),
        ),
    ]
