# Generated by Django 2.1.2 on 2018-11-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0010_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
