# Generated by Django 2.1.2 on 2018-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0011_file_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='safe',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
