# Generated by Django 2.1.2 on 2018-11-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0011_auto_20181121_2217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'token')},
        ),
    ]
