# Generated by Django 2.1.2 on 2018-11-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcv1', '0014_auto_20181123_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryption',
            name='dead_time_check',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.CharField(default='0', max_length=1000000),
        ),
    ]
